### PR TITLE
Update to work with latest slog API

### PR DESCRIPTION
**Pull request by abh**

### CODE REVIEW

**Comment by cyrusaf** [comment]
Thanks for opening this PR! Looks like there were a couple of test failures due to similar slog API changes. If you push up fixes I'll merge this in or I can make the fixes later today when I have more time.

**Comment by abh** [comment]
whoops, I fixed the tests.

**Comment by cyrusaf** [comment]
Thanks!

**Comment by cyrusaf** [comment]
FYI I created a new tag v1.0.1 for Go modules to use. In hindsight I probably should have kept this as v0 until slog went stable.

**Pull request merged**
